name: demo-sklearn-deployment
type: kubernetes
endpoint_name: demo-sklearn-endpoint
app_insights_enabled: true
model: 
  path: model/sklearn_mnist_model.pkl
code_configuration:
  code: script/
  scoring_script: score.py
instance_type: demo-sklearn-instance-type
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: model/conda.yml
request_settings:
  request_timeout_ms: 3000
  max_queue_wait_ms: 3000
resources:
  requests:
    cpu: "0.1"
    memory: "0.1Gi"
  limits:
    cpu: "0.2"
    memory: "0.2Gi"
readiness_probe:
  failure_threshold: 30
  initial_delay: 10
  period: 10
  success_threshold: 1
  timeout: 2
liveness_probe:
  failure_threshold: 30
  initial_delay: 10
  period: 10
  success_threshold: 1
  timeout: 2
scale_settings:
  type: target_utilization
  min_instances: 1
  max_instances: 3
  polling_interval: 10
  target_utilization_percentage: 70
tags:
  endpointName: demo-sklearn-endpoint
  modelName: sklearn-mnist
